export function Methodology() {
  return (
    <article className="flex flex-col gap-5 text-sm leading-relaxed text-gray-300">
      <div>
        <h2 className="text-xl font-semibold text-gray-100">Methodology</h2>
        <p className="mt-2 text-gray-400">
          FrameForecast is a portfolio/demo project. Read this before trusting a number it gives
          you.
        </p>
      </div>

      <section>
        <h3 className="text-base font-medium text-gray-100">
          This is an estimate, not a simulation
        </h3>
        <p>
          Real game and mod performance depends on engine internals, shader compilation, driver
          behavior, your specific save file, and mod interactions that no offline tool can
          compute. FrameForecast does not run the game, does not measure your hardware, and does
          not simulate anything. It returns a statistical estimate produced by a small regression
          model trained on a hand-curated dataset. Treat the number as a rough, directional
          guess &mdash; not a benchmark result.
        </p>
      </section>

      <section>
        <h3 className="text-base font-medium text-gray-100">How the training data was built</h3>
        <p>
          There is no public dataset of controlled, per-mod-combination FPS benchmarks across
          every hardware tier, so this project builds its training data from two pieces, combined
          with documented logic:
        </p>
        <ol className="ml-5 list-decimal">
          <li>
            <strong className="text-gray-200">Baseline (no-mod) FPS figures</strong> for each
            supported game across CPU tier, GPU tier, and resolution. These are approximate,
            representative numbers informed by publicly available benchmark trends for these
            games (the kind of GPU/CPU tier comparisons and resolution-scaling ratios published by
            outlets like TechPowerUp or GamersNexus, and community benchmark threads for older
            titles). They are not scraped from any specific article or table, and they should not
            be read as an exact reproduction of any one source's numbers.
          </li>
          <li>
            <strong className="text-gray-200">A mod-impact model</strong>: every mod in the
            library is tagged with a category (texture overhaul, graphics/shader overhaul,
            lighting/weather overhaul, script-heavy gameplay, NPC/creature density, or lightweight
            tweak), and each category has a reasonably-estimated FPS impact weight, scaled by
            whichever hardware tier that category is most sensitive to (GPU-heavy categories hit
            weaker GPUs harder; CPU-heavy categories hit weaker CPUs harder). Multiple mods stack
            multiplicatively, with a cap so a handful of mods can't estimate an implausible
            near-zero FPS.
          </li>
        </ol>
        <p>
          Training rows are generated by combining these two pieces across every hardware
          combination, plus random mod selections and a small amount of random noise standing in
          for real-world run-to-run variance. That gives the model a training set of a few
          thousand rows to learn from, while being honest that it's a synthesized, documented
          approximation, not a table of measured results.
        </p>
      </section>

      <section>
        <h3 className="text-base font-medium text-gray-100">The model itself</h3>
        <p>
          A <code>RandomForestRegressor</code> (scikit-learn) is trained on the game, CPU/GPU/RAM
          tier, resolution, and mod-category counts, to predict average FPS. The predicted range
          shown on the results page comes from the spread of predictions across the individual
          trees in the forest &mdash; tighter agreement between trees produces a narrower range,
          more disagreement produces a wider one. It's a genuine (if simplified) model-native
          uncertainty measure, not an arbitrary +/- percentage, but it still only reflects the
          model's own confidence, not real-world variance. The feature-importance chart comes
          from the trained model's <code>feature_importances_</code>, grouped into readable
          categories (e.g. every one-hot "game" column rolled into a single "Game" bar).
        </p>
        <p>
          Training and inference code lives in <code>backend/app/ml/</code>. Run{" "}
          <code>python -m app.ml.train_model</code> from <code>backend/</code> to regenerate the
          dataset and retrain from scratch.
        </p>
      </section>

      <section>
        <h3 className="text-base font-medium text-gray-100">What this demonstrates</h3>
        <p>
          This project exists out of genuine interest in the intersection of PC hardware,
          modding, and applied ML &mdash; not a production pattern from my day job. It's meant to
          show an end-to-end ML feature: data curation and documentation, feature engineering,
          model training with a checked-in reproducible training script, an inference API, and a
          results UI that surfaces uncertainty and interpretability instead of hiding them.
        </p>
      </section>

      <section>
        <h3 className="text-base font-medium text-gray-100">Trademark and affiliation notice</h3>
        <p>
          FrameForecast is not affiliated with, endorsed by, or sponsored by any game publisher or
          developer, any GPU/CPU vendor, or any mod author or modding platform referenced in this
          app. NVIDIA, AMD, and Intel are trademarks of their respective owners, as are the game
          titles listed here (The Elder Scrolls V: Skyrim Special Edition, Cyberpunk 2077,
          Minecraft). Named example mods in this app are illustrative labels for a mod category,
          not benchmarks of, or claims about, any specific real mod.
        </p>
      </section>
    </article>
  );
}
